CREATE SCHEMA IF NOT EXISTS user_schema AUTHORIZATION auth;
CREATE TABLE user_schema.user_info (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,


    first_name VARCHAR(255) DEFAULT NULL,
    last_name VARCHAR(255) DEFAULT NULL,
    gender BOOLEAN DEFAULT NULL
);
    
GRANT USAGE ON SCHEMA user_schema TO auth;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA user_schema TO auth;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA user_schema TO auth;


GRANT ALL ON ALL TABLES IN SCHEMA user_schema TO auth;
GRANT ALL ON ALL SEQUENCES IN SCHEMA user_schema TO auth;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA user_schema TO auth;
